# Generated by Django 3.0.4 on 2020-04-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_carimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimages',
            name='img_url',
            field=models.FileField(blank=True, upload_to='account/media_files'),
        ),
    ]
