# Generated by Django 3.0.4 on 2020-04-13 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraddcar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_date_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_self_driver',
            field=models.CharField(max_length=5),
        ),
    ]
