# Generated by Django 3.0.4 on 2020-04-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200413_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddcar',
            name='c_user_city',
            field=models.TextField(default='SOME STRING', verbose_name='Karachi'),
        ),
        migrations.AddField(
            model_name='useraddcar',
            name='c_user_state',
            field=models.TextField(default='SOME STRING', verbose_name='Sindh'),
        ),
    ]
