# Generated by Django 3.0.4 on 2020-04-22 19:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200416_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_user_city',
            field=models.TextField(default='Karachi', verbose_name='Karachi'),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_user_state',
            field=models.TextField(default='Karachi', verbose_name='Sindh'),
        ),
        migrations.AlterField(
            model_name='userextdata',
            name='user_join_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
        ),
        migrations.AlterField(
            model_name='userextdata',
            name='user_location',
            field=models.CharField(default='', max_length=30, verbose_name='Karachi, Sindh, PK'),
        ),
    ]
