# Generated by Django 3.0.4 on 2020-04-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200423_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextdata',
            name='user_location',
            field=models.CharField(max_length=50, verbose_name='Karachi, Sindh, PK'),
        ),
    ]
