# Generated by Django 3.0.4 on 2020-04-23 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200423_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextdata',
            name='user_join_date',
            field=models.DateTimeField(verbose_name=django.utils.timezone.now),
        ),
    ]
