# Generated by Django 3.0.4 on 2020-04-23 18:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200423_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userextdata',
            name='user_join_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
