# Generated by Django 3.0.4 on 2020-04-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20200423_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextdata',
            name='user_location',
            field=models.CharField(default='Karachi, Sindh, PK', max_length=100),
        ),
    ]
