# Generated by Django 3.0.4 on 2020-05-16 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=30)),
                ('car_img', models.ImageField(null=True, upload_to='cars/img')),
            ],
        ),
        migrations.CreateModel(
            name='UserBookCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('post_title', models.CharField(max_length=100)),
                ('city', models.CharField(default='Karachi', max_length=15)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('post_id', models.IntegerField()),
                ('post_user_id', models.IntegerField()),
                ('let', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddCar',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=100)),
                ('c_select_image', models.URLField()),
                ('c_car_image', models.ImageField(null=True, upload_to='posts/img')),
                ('c_car_model', models.CharField(max_length=8)),
                ('c_self_driver', models.CharField(max_length=20)),
                ('c_car_name', models.CharField(max_length=30)),
                ('c_user_city', models.CharField(default='Karachi', max_length=15)),
                ('c_car_color', models.CharField(max_length=15)),
                ('c_car_about', models.TextField()),
                ('c_par_day_price', models.CharField(max_length=20)),
                ('c_car_plate', models.CharField(max_length=20)),
                ('c_post_by_user_name', models.CharField(max_length=20)),
                ('c_post_by_user_phone', models.CharField(max_length=15)),
                ('c_post_by_user_id', models.IntegerField()),
                ('c_post_by_user_pic', models.URLField(default='')),
                ('c_address', models.CharField(max_length=50)),
                ('c_log_2', models.CharField(max_length=30)),
                ('c_let_1', models.CharField(max_length=30)),
                ('c_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
