# Generated by Django 3.0.4 on 2020-12-17 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0005_auto_20201204_1834'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_img', models.CharField(max_length=30)),
                ('car_img', models.ImageField(null=True, upload_to='cars/img')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbc_email', models.CharField(max_length=70)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('email_verify', models.SmallIntegerField()),
                ('status_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserBookCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('phone_no', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('post_title', models.CharField(max_length=100)),
                ('city', models.CharField(default='Karachi', max_length=15)),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('post_id', models.IntegerField()),
                ('post_path', models.URLField(blank=True, max_length=250, null=True)),
                ('booking_update', models.IntegerField(blank=True, null=True)),
                ('status_check', models.BooleanField(default=False)),
                ('post_user_id', models.IntegerField()),
                ('let', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_snt', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddCar',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_title', models.CharField(max_length=100)),
                ('c_select_image', models.ImageField(null=True, upload_to='posts/img')),
                ('c_car_model', models.CharField(max_length=8)),
                ('c_self_driver', models.CharField(max_length=20)),
                ('c_make_by', models.CharField(blank=True, max_length=20, null=True)),
                ('c_car_name', models.CharField(max_length=30)),
                ('c_user_city', models.CharField(default='Karachi', max_length=15)),
                ('c_car_color', models.CharField(max_length=15)),
                ('c_car_about', models.TextField()),
                ('c_par_day_price', models.CharField(max_length=20)),
                ('c_car_plate', models.CharField(max_length=20)),
                ('c_post_by_user_name', models.CharField(max_length=20)),
                ('c_post_by_user_phone', models.CharField(max_length=15)),
                ('c_post_by_user_id', models.IntegerField(blank=True, unique=True)),
                ('c_post_by_user_pic', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('c_address', models.CharField(max_length=200)),
                ('c_log_2', models.CharField(max_length=30)),
                ('c_let_1', models.CharField(max_length=30)),
                ('c_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('c_slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userext', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.UserInformationExt')),
            ],
        ),
        migrations.CreateModel(
            name='SavePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, null=True)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
