# Generated by Django 3.0.4 on 2020-12-18 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_post_by_user_id',
        ),
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_post_by_user_name',
        ),
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_post_by_user_phone',
        ),
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_post_by_user_pic',
        ),
        migrations.CreateModel(
            name='PostsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multi_imgs', models.FileField(max_length=255, null=True, upload_to='posts/multi-img')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAddCar')),
            ],
        ),
    ]
