# Generated by Django 3.0.4 on 2020-05-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_post_by_user_pic',
            field=models.URLField(default='static/img/profile-img.png'),
        ),
    ]
