# Generated by Django 3.0.4 on 2020-12-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201218_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_select_image',
        ),
    ]
