# Generated by Django 3.0.4 on 2020-05-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200519_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_post_by_user_pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
