# Generated by Django 3.0.4 on 2020-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_useraddcar_c_select_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddcar',
            name='c_select_image',
            field=models.ImageField(null=True, upload_to='posts/img'),
        ),
    ]
