# Generated by Django 3.0.4 on 2020-06-02 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_phone', models.CharField(max_length=15)),
                ('user_email', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='useraddcar',
            name='c_car_image',
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_select_image',
            field=models.ImageField(null=True, upload_to='posts/img'),
        ),
    ]
