# Generated by Django 3.0.4 on 2020-12-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraddcar_c_select_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CarsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_by', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='CarImages',
        ),
        migrations.AddField(
            model_name='carsmodel',
            name='make_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.CarsName'),
        ),
    ]
