# Generated by Django 3.0.4 on 2020-12-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201226_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddcar',
            name='c_user_state',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_car_about',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_self_driver',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='useraddcar',
            name='c_user_city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
