# Generated by Django 3.0.4 on 2020-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201227_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_select_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/img'),
        ),
    ]
