# Generated by Django 3.0.4 on 2020-12-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201230_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddcar',
            name='c_admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraddcar',
            name='c_view_counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
