# Generated by Django 3.0.4 on 2021-01-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201230_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddcar',
            name='c_par_day_price',
            field=models.IntegerField(),
        ),
    ]
