# Generated by Django 3.0.4 on 2020-05-16 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformationExt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_phno', models.CharField(max_length=15)),
                ('user_profile_image', models.ImageField(null=True, upload_to='avatar/img')),
                ('user_address', models.CharField(default='Karachi, Sindh, PK', max_length=100)),
                ('user_location', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
