# Generated by Django 3.0.4 on 2020-11-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationext',
            name='user_address',
            field=models.CharField(default='Karachi, Sindh, PK', max_length=100, null=True),
        ),
    ]
