# Generated by Django 3.0.4 on 2020-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20201112_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationext',
            name='user_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
