# Generated by Django 3.0.4 on 2020-12-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20201119_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationext',
            name='user_address',
            field=models.CharField(default='Karachi, Sindh, PK', max_length=100, null=True),
        ),
    ]
