# Generated by Django 3.0.4 on 2020-12-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_auto_20201204_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformationext',
            name='user_profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatar/img'),
        ),
        migrations.DeleteModel(
            name='ProfileImage',
        ),
    ]
