# Generated by Django 3.0.4 on 2020-12-17 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_auto_20201217_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformationext',
            name='user_profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatar/img'),
        ),
    ]
